# Generated by Django 4.2.3 on 2023-07-11 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('numero_cama', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_contrato', models.CharField(max_length=100, unique=True, serialize=False)),
                ('tipo_contrato', models.CharField(choices=[('L', 'Contrato local'), ('G', 'Contrato garantia'), ('C', 'Contrato consolidado')], default='L', max_length=1)),
                ('tipo_servicio_estipulado', models.CharField(choices=[('P/C', 'Servicio preventivo y correctivo'), ('PRV', 'Servicio  preventivo'), ('N/A', 'Proveedor no brinda servicio')], default='PRV', max_length=3)),
                ('fecha_vencimiento', models.DateField()),
                ('num_servicios', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo_medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nacional_inv', models.CharField(max_length=100, unique=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=255, null=True)),
                ('numero_serie', models.CharField(max_length=255, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50, null=True)),
                ('cama', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.cama')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala_hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.PositiveIntegerField()),
                ('encargado', models.CharField(max_length=100)),
                ('nombre_sala', models.CharField(max_length=100)),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('D', 'Diagnostico'), ('R', 'Refaccion')], default='P', max_length=1)),
                ('tipo_orden', models.CharField(choices=[('A', 'Orden agendada'), ('E', 'Orden espontanea'), ('B', 'Bitacora mensual')], default='E', max_length=1)),
                ('estatus', models.CharField(choices=[('FUN', 'Equipo funcional'), ('OUT', 'Equipo fuera de servicio'), ('N/A', 'No se realizo servicio')], default='FUN', max_length=3)),
                ('responsable', models.CharField(max_length=100)),
                ('autorizo_jefe_biomedica', models.BooleanField()),
                ('autorizo_jefe_conservacion', models.BooleanField()),
                ('orden_escaneada', models.FileField(null=True, upload_to='')),
                ('descripcion_servicio', models.CharField(max_length=800)),
                ('equipo_complementario', models.CharField(max_length=800, null=True)),
                ('ing_realizo', models.CharField(max_length=100)),
                ('fallo_paciente', models.BooleanField()),
                ('equipo_medico', models.ManyToManyField(related_name='equipo_orden', to='inventario.equipo_medico')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='cama',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.sala_hospital'),
        ),
    ]
