# Generated by Django 4.2.4 on 2023-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('COM', 'Evento atendido'), ('PEN', 'Evento pendiente')], default='COM', max_length=3),
            preserve_default=False,
        ),
    ]
