# Generated by Django 4.2.4 on 2023-10-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="equipo_medico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Evento_equipo",
                to="inventario.equipo_medico",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="tipo_evento",
            field=models.CharField(
                choices=[
                    ("CONTR", "Vencimiento de contrato"),
                    ("SERVC", "Servicio preventivo agendado"),
                    ("CAPAC", "Curso de capacitacion agendada"),
                    ("CHECK", "Chequeo al equipo agendado"),
                ],
                max_length=5,
            ),
        ),
    ]
