# Generated by Django 4.2.4 on 2023-10-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("CONTR", "Vencimiento de contrato"),
                            ("SERVC", "Servicio agendado"),
                            ("CAPAC", "Curso de capacitacion agendada"),
                            ("CHECK", "Chequeo al equipo agendado"),
                        ],
                        max_length=5,
                    ),
                ),
                ("descripcion", models.CharField(max_length=50, null=True)),
                (
                    "contrato",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.contrato",
                    ),
                ),
                (
                    "equipo_medico",
                    models.ManyToManyField(
                        related_name="Evento_equipo", to="inventario.equipo_medico"
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
            },
        ),
    ]
