# Generated by Django 4.2.4 on 2023-10-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0002_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="prueba_funcionamiento",
            field=models.CharField(
                choices=[
                    ("P", "EL equipo paso la prueba de funcionamiento correctamente"),
                    ("N", "El equipo no paso prueba de funcionamiento"),
                ],
                default="P",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
