# Generated by Django 4.2.4 on 2023-10-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0002_alter_evento_equipo_medico_alter_evento_tipo_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo_medico",
            name="carta_obsolescencia_tercero",
            field=models.FileField(null=True, upload_to="Anexos"),
        ),
        migrations.AddField(
            model_name="equipo_medico",
            name="dictamen_tecnico_propio",
            field=models.FileField(null=True, upload_to="Anexos"),
        ),
        migrations.AddField(
            model_name="equipo_medico",
            name="minuta_baja",
            field=models.FileField(null=True, upload_to="Anexos"),
        ),
        migrations.AlterField(
            model_name="equipo_medico",
            name="estado",
            field=models.CharField(
                choices=[
                    ("FUNC", "Equipo funcional"),
                    ("OUT", "Equipo fuera de servicio"),
                    ("SERV", "Equipo en mantenimiento"),
                    ("BAJA", "Equipo en proceso de baja"),
                ],
                default="FUNC",
                max_length=4,
            ),
        ),
    ]
