# Generated by Django 4.2.3 on 2023-07-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_contrato_num_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('L', 'Contrato local'), ('G', 'Contrato garantia'), ('C', 'Contrato consolidado')], default='L', max_length=1, null=True),
        ),
    ]
