# Generated by Django 4.2.4 on 2023-10-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_reporteusuario_equipo_complementario'),
        ('inventario', '0003_checklist_prueba_funcionamiento'),
    ]

    operations = [
    ]
