# Generated by Django 4.2.3 on 2023-07-12 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_contrato_tipo_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.PositiveIntegerField(null=True)),
                ('encargado', models.CharField(max_length=100)),
                ('nombre_sala', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='sala_hospital',
            name='especialidad',
        ),
        migrations.AlterField(
            model_name='equipo_medico',
            name='cama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.cama'),
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.AddField(
            model_name='equipo_medico',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.area_hospital'),
        ),
        migrations.AlterField(
            model_name='cama',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.area_hospital'),
        ),
        migrations.DeleteModel(
            name='Sala_hospital',
        ),
    ]
