# Generated by Django 4.2.3 on 2023-07-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_area_hospital_remove_sala_hospital_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_hospital',
            name='encargado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
