# Generated by Django 4.2.4 on 2023-10-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_merge_20231023_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteusuario',
            name='fecha_entrega',
            field=models.DateTimeField(default='2023-10-23T12:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='prueba_funcionamiento',
            field=models.CharField(choices=[('P', 'El equipo paso la prueba de funcionamiento correctamente'), ('N', 'El equipo no paso prueba de funcionamiento')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reporteusuario',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('COM', 'Atendido'), ('CER', 'Cerrado')], default='PEN', max_length=3),
        ),
    ]
