# Generated by Django 4.2.4 on 2023-10-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_reporteusuario_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteusuario',
            name='fecha_entrega',
            field=models.DateTimeField(null=True),
        ),
    ]
