# Generated by Django 4.2.4 on 2023-10-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_reporteusuario_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteusuario',
            name='fecha_entrega',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
