# Generated by Django 4.2.3 on 2023-07-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_area_hospital_edificio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area_hospital',
            name='encargado',
        ),
    ]
