# Generated by Django 4.2.3 on 2023-07-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_area_hospital_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo_medico',
            name='estado',
            field=models.CharField(choices=[('FUNC', 'Equipo funcional'), ('OUT', 'Equipo fuera de servicio'), ('SERV', 'Equipo en mantenimiento')], default='FUNC', max_length=4),
        ),
    ]
