# Generated by Django 4.2.3 on 2023-07-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_equipo_medico_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area_hospital',
            options={'ordering': ['nombre_sala']},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['proveedor']},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre_proveedor']},
        ),
        migrations.RemoveField(
            model_name='area_hospital',
            name='edificio',
        ),
        migrations.RemoveField(
            model_name='area_hospital',
            name='numero_sala',
        ),
    ]
