# Generated by Django 4.2.3 on 2023-07-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_proveedor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camas_area', to='inventario.area_hospital'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_contrato', to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='equipo_medico',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_area', to='inventario.area_hospital'),
        ),
        migrations.AlterField(
            model_name='equipo_medico',
            name='cama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_cama', to='inventario.cama'),
        ),
        migrations.AlterField(
            model_name='equipo_medico',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_contrato', to='inventario.contrato'),
        ),
    ]
