# Generated by Django 4.2.3 on 2023-07-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_cama_sala_alter_contrato_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_servicio',
            name='numero_orden',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orden_servicio',
            name='tipo_orden',
            field=models.CharField(choices=[('A', 'Orden agendada'), ('E', 'Orden espontanea'), ('B', 'Bitacora')], default='E', max_length=1),
        ),
    ]
