# Generated by Django 4.2.3 on 2023-07-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_orden_servicio_numero_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_servicio',
            name='num_mantenimiento_preventivo',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
