# Generated by Django 4.2.3 on 2023-07-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_alter_orden_servicio_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_servicio',
            name='descripcion_servicio',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='orden_servicio',
            name='equipo_complementario',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
