# Generated by Django 4.2.3 on 2023-07-31 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0017_alter_orden_servicio_descripcion_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area_hospital',
            name='responsable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_area', to=settings.AUTH_USER_MODEL),
        ),
    ]
