# Generated by Django 4.2.3 on 2023-07-31 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0018_area_hospital_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area_hospital',
            name='responsable',
        ),
        migrations.AddField(
            model_name='area_hospital',
            name='responsable',
            field=models.ManyToManyField(null=True, related_name='responsable_area', to=settings.AUTH_USER_MODEL),
        ),
    ]
