# Generated by Django 4.2.3 on 2023-08-01 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0019_remove_area_hospital_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_hospital',
            name='responsable',
            field=models.ManyToManyField(related_name='responsable_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipo_medico',
            name='marca',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
