# Generated by Django 4.2.3 on 2023-08-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_alter_area_hospital_responsable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('COM', 'Completado'), ('PRO', 'En proceso')], default='PEN', max_length=3)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('falla', models.CharField(choices=[('NO/ENC', 'El equipo no enciende'), ('ALARMA', 'El equipo marca error o alguna alarma'), ('SENSOR', 'Un sensor esta fallando(Brazalette de PANI, sensor de SPO2, Sensores ECG, etc.)'), ('NO/TRB', 'El equipo no trabaja de forma que deberia(No funcionan perillas, botones, pantalla tactil, etc.)'), ('PAPEL', 'Hace falta papel')], max_length=6)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('solucion_tecnico', models.CharField(max_length=500, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='area_reporte', to='inventario.area_hospital')),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_reporte', to='inventario.equipo_medico')),
            ],
        ),
    ]
