# Generated by Django 4.2.3 on 2023-08-02 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_alter_reporteusuario_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden_servicio',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='checklist',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
