# Generated by Django 4.2.3 on 2023-08-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_alter_orden_servicio_options_checklist_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='observaciones',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
