# Generated by Django 4.2.3 on 2023-08-02 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_alter_checklist_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='desempeño_general',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
