# Generated by Django 4.2.3 on 2023-08-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_alter_checklist_desempeño_general'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AlterModelOptions(
            name='reporteusuario',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AlterField(
            model_name='reporteusuario',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('COM', 'Completado')], default='PEN', max_length=3),
        ),
    ]
