# Generated by Django 4.2.3 on 2023-08-03 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0026_alter_checklist_options_alter_reporteusuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteusuario',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_reporte', to=settings.AUTH_USER_MODEL),
        ),
    ]
