# Generated by Django 4.2.4 on 2023-08-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_reporteusuario_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_servicio',
            name='orden_escaneada',
        ),
        migrations.CreateModel(
            name='PDFOrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='UMAE_DB/media')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_escaneada', to='inventario.orden_servicio')),
            ],
        ),
    ]
