# Generated by Django 4.2.4 on 2023-08-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_remove_orden_servicio_orden_escaneada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_servicio',
            name='orden_escaneada',
            field=models.FileField(null=True, upload_to='UMAE_DB/media'),
        ),
        migrations.DeleteModel(
            name='PDFOrdenServicio',
        ),
    ]
