# Generated by Django 4.2.4 on 2023-08-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_alter_orden_servicio_orden_escaneada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteusuario',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('COM', 'Atendido')], default='PEN', max_length=3),
        ),
    ]
