# Generated by Django 4.2.4 on 2023-08-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_alter_reporteusuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_servicio',
            name='orden_escaneada',
            field=models.FileField(null=True, upload_to='Ordenes_servicio'),
        ),
    ]
