# Generated by Django 4.2.4 on 2023-08-22 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_orden_servicio_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_servicio',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='orden_servicio',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_orden', to='inventario.contrato'),
        ),
    ]
