# Generated by Django 4.2.4 on 2023-08-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_remove_orden_servicio_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo_medico',
            name='cama',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
