# Generated by Django 4.2.4 on 2023-08-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_equipo_medico_cama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo_medico',
            old_name='cama',
            new_name='cama_equipo',
        ),
    ]
