# Generated by Django 4.2.4 on 2023-08-26 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0038_rename_cama_equipo_equipo_medico_cama_delete_cama'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteusuario',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.orden_servicio'),
        )
    ]
