# Generated by Django 4.2.4 on 2023-09-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0040_alter_checklist_desempeño_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        )
    ]
