# Generated by Django 4.2.4 on 2023-09-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0041_checklist_ultima_modificacion_delete_cama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='ultima_modificacion',
        )
    ]
