# Generated by Django 4.2.3 on 2023-07-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('Ingeniero', 'Ingeniero'), ('Jefe', 'Jefe')], default='Jefe', max_length=9),
            preserve_default=False,
        ),
    ]
